-- Smilish Group — Demo Content Seed
-- Auto-generated from the site's original placeholder content. Run this
-- AFTER supabase/schema.sql, once, in Supabase's SQL Editor, so your live
-- site isn't empty before you've added real products/properties yourself.
-- Safe to skip entirely if you'd rather start empty and add everything
-- through /admin instead.

-- Fashion Products
insert into fashion_products (name, slug, description, price, category, fabric, sizes, colors, stock_quantity, sku, featured, status) values ('Royal Navy Agbada', 'royal-navy-agbada', 'A ceremonial agbada in deep navy cashmere with hand-worked gold embroidery along the collar and cuffs. Tailored fully custom to your measurements for weddings, chieftaincy and formal occasions.', 185000, 'Agbada', 'Hand-embroidered Cashmere', ARRAY['M', 'L', 'XL', 'XXL', 'Custom'], ARRAY['Navy', 'Gold Trim'], 6, 'SF-AGB-001', true, 'Published') on conflict (slug) do nothing;
insert into fashion_products (name, slug, description, price, category, fabric, sizes, colors, stock_quantity, sku, featured, status) values ('Obsidian Senator Set', 'obsidian-senator-set', 'A sharply tailored two-piece senator set built for boardrooms and formal events, finished with a structured collar and mother-of-pearl buttons.', 95000, 'Senator Wear', 'Italian Wool Blend', ARRAY['S', 'M', 'L', 'XL', 'Custom'], ARRAY['Black', 'Charcoal'], 12, 'SF-SEN-014', true, 'Published') on conflict (slug) do nothing;
insert into fashion_products (name, slug, description, price, category, fabric, sizes, colors, stock_quantity, sku, featured, status) values ('Gilded Native Shirt', 'gilded-native-shirt', 'Breathable guinea brocade native shirt with gold thread detailing at the neckline — a versatile piece for Friday wear and casual celebrations.', 42000, 'Native Shirts', 'Premium Cotton Guinea Brocade', ARRAY['S', 'M', 'L', 'XL'], ARRAY['White/Gold', 'Navy/Gold'], 20, 'SF-NAT-032', true, 'Published') on conflict (slug) do nothing;
insert into fashion_products (name, slug, description, price, category, fabric, sizes, colors, stock_quantity, sku, featured, status) values ('Heritage Kaftan', 'heritage-kaftan', 'A relaxed-fit kaftan cut from a silk-cotton blend that drapes cleanly — comfortable enough for daily wear, sharp enough for guests.', 68000, 'Kaftans', 'Silk-Cotton Blend', ARRAY['M', 'L', 'XL', 'Custom'], ARRAY['Ivory', 'Deep Navy'], 9, 'SF-KAF-009', false, 'Published') on conflict (slug) do nothing;
insert into fashion_products (name, slug, description, price, category, fabric, sizes, colors, stock_quantity, sku, featured, status) values ('Monogram Street Hoodie', 'monogram-street-hoodie', 'Heavyweight hoodie with an embroidered SG monogram at the chest and a boxy, oversized fit true to Smilish streetwear proportions.', 28000, 'Streetwear', 'Heavyweight French Terry', ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Black', 'Navy'], 34, 'SF-STR-101', true, 'Published') on conflict (slug) do nothing;
insert into fashion_products (name, slug, description, price, category, fabric, sizes, colors, stock_quantity, sku, featured, status) values ('Atelier Joggers', 'atelier-joggers', 'Tapered joggers with a ribbed cuff and side-seam pocket, designed as the everyday counterpart to the Monogram collection.', 22000, 'Streetwear', 'Brushed Cotton Fleece', ARRAY['S', 'M', 'L', 'XL'], ARRAY['Black', 'Stone Grey'], 0, 'SF-STR-108', false, 'Out of Stock') on conflict (slug) do nothing;
insert into fashion_products (name, slug, description, price, category, fabric, sizes, colors, stock_quantity, sku, featured, status) values ('Corporate Oxford Shirt', 'corporate-oxford-shirt', 'A precision-cut Oxford shirt for corporate wardrobes and staff uniforms, available for bulk order with company branding on request.', 32000, 'Corporate Wear', 'Egyptian Cotton', ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['White', 'Sky Blue', 'Navy'], 18, 'SF-COR-021', false, 'Published') on conflict (slug) do nothing;
insert into fashion_products (name, slug, description, price, category, fabric, sizes, colors, stock_quantity, sku, featured, status) values ('Midnight Wedding Kaftan', 'midnight-wedding-kaftan', 'A statement kaftan for grooms and guests, hand-embellished with gold thread along the neckline and cuffs — built for the reception, not just the ceremony.', 145000, 'Wedding and Event Wear', 'Embellished Silk', ARRAY['M', 'L', 'XL', 'Custom'], ARRAY['Midnight Navy', 'Gold Embroidery'], 4, 'SF-WED-005', true, 'Published') on conflict (slug) do nothing;
insert into fashion_products (name, slug, description, price, category, fabric, sizes, colors, stock_quantity, sku, featured, status) values ('Signature Cap', 'signature-cap', 'A structured six-panel cap with a subtly embroidered SG monogram — the easiest way into the Smilish streetwear line.', 12000, 'Streetwear', 'Cotton Twill', ARRAY['One Size'], ARRAY['Black', 'Navy', 'Stone'], 41, 'SF-STR-115', false, 'Published') on conflict (slug) do nothing;
insert into fashion_products (name, slug, description, price, category, fabric, sizes, colors, stock_quantity, sku, featured, status) values ('Personal Styling & Fitting Session', 'consultation-fitting', 'A one-on-one session with a Smilish stylist to plan an outfit, take measurements, or refine a wardrobe for an upcoming event — fee is credited toward any order placed the same day.', 15000, 'Fashion Consultation', 'N/A', '{}', '{}', 999, 'SF-CON-001', false, 'Published') on conflict (slug) do nothing;

-- Fashion Projects
insert into fashion_projects (title, slug, description, category, client_name, project_date, featured, status) values ('Adeyemi Wedding Agbada Collection', 'adeyemi-wedding-agbada', 'A five-piece agbada commission for a groom and his train, unifying navy and gold across five custom fits for the traditional ceremony.', 'Wedding and Event Wear', 'Private Client', '2025-11-02', true, 'Published') on conflict (slug) do nothing;
insert into fashion_projects (title, slug, description, category, client_name, project_date, featured, status) values ('Lagos Fintech Staff Uniforms', 'lagos-fintech-uniforms', '60 units of branded corporate shirts and blazers produced and fitted for a fintech company''s Lagos head office launch.', 'Corporate Wear', 'Confidential Fintech Client', '2025-09-14', true, 'Published') on conflict (slug) do nothing;
insert into fashion_projects (title, slug, description, category, client_name, project_date, featured, status) values ('Streetwear Capsule Vol. 2', 'streetwear-capsule-vol2', 'An in-house capsule drop of 200 units across hoodies, joggers and caps, styled and shot for the Smilish Instagram launch.', 'Streetwear', null, '2025-06-30', false, 'Published') on conflict (slug) do nothing;

-- Automation Services
insert into automation_services (name, slug, summary, description, features, industries, pricing_type, featured, status) values ('AI Customer Service Agent', 'ai-customer-service-agent', 'A 24/7 AI agent that answers customer questions, takes orders and escalates when needed.', 'Deployed across WhatsApp, Instagram and your website, the AI Customer Service Agent understands your product catalogue, answers repetitive questions instantly, and hands off to a human teammate the moment a conversation needs one.', ARRAY['24/7 multi-channel coverage', 'Trained on your own knowledge base', 'Order capture and status updates', 'Human hand-off with full conversation context'], ARRAY['Food & Restaurants', 'Retail', 'Services'], 'Monthly Retainer', true, 'Published') on conflict (slug) do nothing;
insert into automation_services (name, slug, summary, description, features, industries, pricing_type, featured, status) values ('AI Sales Assistant', 'ai-sales-assistant', 'Qualifies inbound leads, answers objections and books calls automatically.', 'The AI Sales Assistant engages every inbound lead within seconds, asks the qualifying questions your sales team would ask, and books a call directly onto your calendar for the leads worth a conversation.', ARRAY['Automatic lead qualification', 'Objection handling scripts', 'Calendar booking integration', 'CRM sync on every conversation'], ARRAY['B2B Services', 'Real Estate', 'Automation Clients'], 'Custom Quote', true, 'Published') on conflict (slug) do nothing;
insert into automation_services (name, slug, summary, description, features, industries, pricing_type, featured, status) values ('AI Booking Agent', 'ai-booking-agent', 'Handles appointment and inspection bookings without back-and-forth messages.', 'Whether it''s a property inspection, a fitting appointment or a consultation call, the AI Booking Agent finds an open slot, confirms it with the customer and syncs it to your calendar automatically.', ARRAY['Real-time calendar availability', 'Automatic reminders and reschedules', 'Two-way WhatsApp and email confirmation', 'No-show follow-up sequences'], ARRAY['Real Estate', 'Fashion Consultations', 'Clinics & Services'], 'Monthly Retainer', true, 'Published') on conflict (slug) do nothing;
insert into automation_services (name, slug, summary, description, features, industries, pricing_type, featured, status) values ('AI Knowledge Assistant', 'ai-knowledge-assistant', 'An internal assistant trained on your company''s documents, SOPs and FAQs.', 'Give your team an assistant that already knows your SOPs, pricing sheets and policies — cutting down the time spent digging through documents or waiting on a manager to reply.', ARRAY['Trained on internal documents', 'Slack, WhatsApp or web access', 'Always up to date as documents change', 'Usage and gap analytics'], ARRAY['Any growing team'], 'One-Time Build', false, 'Published') on conflict (slug) do nothing;

-- Automation Projects (Case Studies)
insert into automation_projects (title, slug, client_business, problem, solution, workflow_tools, results, project_date, featured, status) values ('24/7 Order & Support Automation for a Food Ordering Brand', 'item7go-order-automation', 'Food Ordering Company', 'Orders and customer questions were handled manually across phone and DM, causing missed orders and slow replies during peak hours.', 'Built an AI customer service and ordering agent that handles menu questions, takes full orders, and routes delivery issues to a human when needed.', ARRAY['n8n', 'LLM API', 'WhatsApp Business API', 'Google Sheets'], ARRAY['Faster response times during peak hours', 'Orders now captured automatically around the clock', 'Fewer repetitive questions reaching the support line'], '2025-10-01', true, 'Published') on conflict (slug) do nothing;
insert into automation_projects (title, slug, client_business, problem, solution, workflow_tools, results, project_date, featured, status) values ('Automated Lead Qualification & Outreach Pipeline', 'b2b-lead-qualification-workflow', 'B2B Services Company', 'The sales team was spending hours manually researching and qualifying leads before any outreach began.', 'Built an automated research and qualification workflow that scores inbound and outbound leads and routes qualified ones straight into the CRM.', ARRAY['n8n', 'CRM Integration', 'Email Automation'], ARRAY['Reduced manual research time', 'Consistent lead scoring', 'Cleaner CRM pipeline'], '2025-07-20', true, 'Published') on conflict (slug) do nothing;

-- Properties
insert into properties (title, slug, description, price, price_unit, location, state, city, area_sqm, property_type, transaction_type, bedrooms, bathrooms, land_size_sqm, features, documentation_status, agent_name, agent_phone, status, featured, published) values ('4-Bedroom Detached Duplex, Lekki Phase 1', 'lekki-phase-1-4bed-duplex', 'A fully finished 4-bedroom detached duplex with a boys'' quarters, ensuite bedrooms and a private compound in a serene, gated close within Lekki Phase 1.', 185000000, 'total', 'Lekki Phase 1', 'Lagos', 'Lekki', 450, 'House', 'For Sale', 4, 5, 650, ARRAY['Boys'' Quarters', 'Fitted Kitchen', '24/7 Estate Security', 'Parking for 4 Cars'], 'Certificate of Occupancy (C of O)', 'Chidera Okonkwo', '+234 000 000 0001', 'Available', true, true) on conflict (slug) do nothing;
insert into properties (title, slug, description, price, price_unit, location, state, city, area_sqm, property_type, transaction_type, bedrooms, bathrooms, land_size_sqm, features, documentation_status, agent_name, agent_phone, status, featured, published) values ('Furnished Office Suite, Ikeja GRA', 'ikeja-gra-office-suite', 'A ready-to-move-in 220sqm office suite on the second floor of a modern commercial building, with dedicated parking and backup power.', 4500000, 'per year', 'Ikeja GRA', 'Lagos', 'Ikeja', 220, 'Office', 'For Rent', null, null, null, ARRAY['24/7 Power Backup', 'Elevator Access', 'Dedicated Parking', 'Fibre Internet Ready'], 'Deed of Sublease Available', 'Tunde Bakare', '+234 000 000 0002', 'Available', true, true) on conflict (slug) do nothing;
insert into properties (title, slug, description, price, price_unit, location, state, city, area_sqm, property_type, transaction_type, bedrooms, bathrooms, land_size_sqm, features, documentation_status, agent_name, agent_phone, status, featured, published) values ('1,000 sqm Waterfront Land, Epe', 'epe-waterfront-land', 'Dry, fenced waterfront land in a fast-appreciating corridor of Epe, suitable for a private residence or short-let development.', 28000000, 'total', 'Agemowo, Epe', 'Lagos', 'Epe', 1000, 'Land', 'For Sale', null, null, 1000, ARRAY['Waterfront', 'Fenced & Gated', 'Dry Land', 'Good Road Access'], 'Registered Survey & Deed of Assignment', 'Chidera Okonkwo', '+234 000 000 0001', 'Available', true, true) on conflict (slug) do nothing;
insert into properties (title, slug, description, price, price_unit, location, state, city, area_sqm, property_type, transaction_type, bedrooms, bathrooms, land_size_sqm, features, documentation_status, agent_name, agent_phone, status, featured, published) values ('2-Bedroom Serviced Apartment, Victoria Island', 'victoria-island-2bed-apartment', 'A serviced 2-bedroom apartment with a full-time concierge, gym and pool access, ideal for young professionals and short-let investors.', 6500000, 'per year', 'Victoria Island', 'Lagos', 'Victoria Island', 120, 'Apartment', 'For Rent', 2, 3, null, ARRAY['Concierge', 'Gym & Pool Access', 'Serviced', 'Standby Generator'], 'Tenancy Agreement', 'Tunde Bakare', '+234 000 000 0002', 'Reserved', false, true) on conflict (slug) do nothing;
insert into properties (title, slug, description, price, price_unit, location, state, city, area_sqm, property_type, transaction_type, bedrooms, bathrooms, land_size_sqm, features, documentation_status, agent_name, agent_phone, status, featured, published) values ('Retail Shop Space, Guzape District', 'abuja-guzape-shop', 'A 60sqm ground-floor retail shop on a busy commercial strip in Guzape, previously operated as a boutique showroom.', 2200000, 'per year', 'Guzape District', 'FCT — Abuja', 'Abuja', 60, 'Shop', 'For Rent', null, null, null, ARRAY['High Foot Traffic', 'Street-Facing Frontage', 'Shared Parking'], 'Tenancy Agreement', 'Amara Nwosu', '+234 000 000 0003', 'Available', false, true) on conflict (slug) do nothing;
insert into properties (title, slug, description, price, price_unit, location, state, city, area_sqm, property_type, transaction_type, bedrooms, bathrooms, land_size_sqm, features, documentation_status, agent_name, agent_phone, status, featured, published) values ('Serviced Plots, Smilish Gardens Estate', 'ibeju-lekki-estate-plots', '500sqm serviced plots inside a developing gated estate along the Lekki-Epe corridor, with allocation available on select rows.', 15000000, 'total', 'Smilish Gardens Estate', 'Lagos', 'Ibeju-Lekki', 500, 'Estate', 'Investment', null, null, 500, ARRAY['Gated Estate', 'Perimeter Fencing', 'Estate Road Network', 'Flexible Payment Plan'], 'Registered Survey — C of O in View', 'Amara Nwosu', '+234 000 000 0003', 'Available', true, true) on conflict (slug) do nothing;
insert into properties (title, slug, description, price, price_unit, location, state, city, area_sqm, property_type, transaction_type, bedrooms, bathrooms, land_size_sqm, features, documentation_status, agent_name, agent_phone, status, featured, published) values ('3-Bedroom Terrace Duplex, Ajah', 'ajah-3bed-terrace', 'A newly built 3-bedroom terrace duplex inside a serviced estate off the Lekki-Epe expressway, walking distance from the estate mall and school.', 78000000, 'total', 'Off Lekki-Epe Expressway', 'Lagos', 'Ajah', 220, 'House', 'For Sale', 3, 4, 300, ARRAY['Estate Mall Nearby', 'Ensuite Bedrooms', 'Fitted Kitchen', '24/7 Estate Security'], 'Deed of Assignment — Governor''s Consent in Progress', 'Chidera Okonkwo', '+234 000 000 0001', 'Available', false, true) on conflict (slug) do nothing;
insert into properties (title, slug, description, price, price_unit, location, state, city, area_sqm, property_type, transaction_type, bedrooms, bathrooms, land_size_sqm, features, documentation_status, agent_name, agent_phone, status, featured, published) values ('Commercial Complex Floor, Wuse 2', 'wuse-2-commercial-complex', 'A full 300sqm floor in a busy commercial complex, previously fitted as a bank branch — suitable for a showroom, clinic or corporate office.', 12000000, 'per year', 'Wuse 2', 'FCT — Abuja', 'Abuja', 300, 'Commercial', 'For Rent', null, null, null, ARRAY['Previously Fitted', 'Standby Generator', 'Ample Parking', 'High Visibility Frontage'], 'Tenancy Agreement', 'Amara Nwosu', '+234 000 000 0003', 'Available', false, true) on conflict (slug) do nothing;
insert into properties (title, slug, description, price, price_unit, location, state, city, area_sqm, property_type, transaction_type, bedrooms, bathrooms, land_size_sqm, features, documentation_status, agent_name, agent_phone, status, featured, published) values ('Luxury Penthouse, Banana Island', 'banana-island-luxury-penthouse', 'A five-bedroom penthouse with private pool and skyline views, fully finished with imported fittings throughout — one of a limited number in the building.', 950000000, 'total', 'Banana Island', 'Lagos', 'Ikoyi', 680, 'Apartment', 'For Sale', 5, 6, null, ARRAY['Private Pool', 'Skyline Views', 'Imported Fittings', 'Private Elevator Access'], 'Certificate of Occupancy (C of O)', 'Tunde Bakare', '+234 000 000 0002', 'Reserved', true, true) on conflict (slug) do nothing;

